# Generated by Django 5.0.3 on 2024-07-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_book_description_publisher_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
